name: milestone
on:
  schedule:
  # UTC時間で設定
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  create-milestone:
    runs-on: ubuntu-latest
    name: 'create milestone'
    steps:
      - uses: actions/checkout@master
      - name: install jq
        run: |
          sudo apt update
          sudo apt install -y jq
      - id: milestone
        name: create milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          due_time=$(date -d"tue 14 days" +"%Y-%m-%dT23:59:59Z")
          title=release_$(date -d"tue 14 days" +"%Y%m%d")
          milestone=`.github/workflows/bin/create-milestone.sh ${{ github.repository }} ${title} ${due_time}`
          echo ::set-output name=milestone_id::$milestone
